---
project:
  type: website

execute:
  cache: true
  freeze: auto

format:
  html:
    css: styling/site-wide.css
    theme: darkly
    include-in-header:
      - text: |
          <link href="site_libs/quarto-contrib/fontawesome6-6.7.2/all.min.css" rel="stylesheet">
          <script src="https://cdn.jsdelivr.net/npm/tsparticles/dist/tsparticles.min.js"></script>
          <script src="particles/app.js"></script>
    include-before-body:
      - text: |
          <div id="tsparticles"></div>
  revealjs:
    auto-play-media: true
    auto-stretch: false
    callout-appearance: simple
    code-copy: true
    css: styling/talks.css
    filters:
      - _filters/slugify.lua
    footer: "{{< meta title >}} - [Back to talks](/talks.html)"
    hash-type: number
    history: false
    incremental: true
    link-external-filter: ^https:\/\/connoraird\.github\.io
    link-external-icon: true
    logo: assets/favicon.ico
    mermaid:
      theme: dark
    menu:
      hideMissingTitles: true
      useTextContentForMissingTitles: false
    mobile-view-distance: 10
    slide-number: c
    theme: default
    transition: fade
    view-distance: 10

resources:
  - particles

website:
  favicon: assets/favicon.ico
  navbar:
    collapse-below: lg
    logo: https://www.gravatar.com/avatar/a24925988bd171effa08b9bbe9a9cb16cf3f6e902f6e348857d4e509a4810ad1?s=1000
    logo-alt: "Connor Aird"
    left:
      - text: Talks
        href: talks.qmd
    tools:
      - text: Email
        icon: envelope
        href: mailto:c.aird@ucl.ac.uk
      - text: GitHub
        icon: github
        href: https://github.com/connoraird
      - text: Linkedin
        icon: linkedin
        href: https://www.linkedin.com/in/connoraird/
  site-url: https://connoraird.github.io
  title: Connor Aird
